import './src/assets/css/stylesheet.css'
import './src/assets/css/main.css'
import './src/assets/css/colors.css'
// import './src/assets/css/noscript.css'
import './src/assets/css/rotateim.css'
import './src/assets/css/service.css'
import './src/assets/js/main'
import './src/assets/js/contact_us'
import './src/assets/js/rotateim'
import './src/assets/js/service'
import './src/assets/js/util'